[book]
title = "Vibemon Documentation"
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/stencil-hq/vibemon"
site-url = "https://stencil-hq.github.io/vibemon/"
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/sdk-language.css", "theme/custom.css"]
additional-js = ["theme/sdk-language.js"]