// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmon/v1/bridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gRPC-over-WebSocket bridge for clients without native HTTP/2 (browsers).
//
// One RPC per WebSocket connection to `GET /grpc` (auth: bearer header when
// the client can set one, else the same `?token=` query mechanism the old WS
// endpoints used; UDS peer-cred bypass unchanged). Every WS binary message in
// EITHER direction is exactly one encoded BridgeFrame; text messages are
// protocol errors.
//
//	client:  call → message* → half_close
//	server:  message* → end   (then closes the socket)
//
// `message` payloads are single encoded gRPC messages WITHOUT the 5-byte
// gRPC wire prefix — WS message boundaries provide framing. The server
// bridges frames onto the in-process gRPC services; `end` mirrors the RPC's
// status and trailers (including `vmon-code`).
type BridgeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*BridgeFrame_Call
	//	*BridgeFrame_Message
	//	*BridgeFrame_HalfClose
	//	*BridgeFrame_End
	Frame         isBridgeFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeFrame) Reset() {
	*x = BridgeFrame{}
	mi := &file_vmon_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeFrame) ProtoMessage() {}

func (x *BridgeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeFrame.ProtoReflect.Descriptor instead.
func (*BridgeFrame) Descriptor() ([]byte, []int) {
	return file_vmon_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeFrame) GetFrame() isBridgeFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *BridgeFrame) GetCall() *BridgeCall {
	if x != nil {
		if x, ok := x.Frame.(*BridgeFrame_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *BridgeFrame) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Frame.(*BridgeFrame_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *BridgeFrame) GetHalfClose() *BridgeHalfClose {
	if x != nil {
		if x, ok := x.Frame.(*BridgeFrame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return nil
}

func (x *BridgeFrame) GetEnd() *BridgeEnd {
	if x != nil {
		if x, ok := x.Frame.(*BridgeFrame_End); ok {
			return x.End
		}
	}
	return nil
}

type isBridgeFrame_Frame interface {
	isBridgeFrame_Frame()
}

type BridgeFrame_Call struct {
	Call *BridgeCall `protobuf:"bytes,1,opt,name=call,proto3,oneof"`
}

type BridgeFrame_Message struct {
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type BridgeFrame_HalfClose struct {
	HalfClose *BridgeHalfClose `protobuf:"bytes,3,opt,name=half_close,json=halfClose,proto3,oneof"`
}

type BridgeFrame_End struct {
	End *BridgeEnd `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*BridgeFrame_Call) isBridgeFrame_Frame() {}

func (*BridgeFrame_Message) isBridgeFrame_Frame() {}

func (*BridgeFrame_HalfClose) isBridgeFrame_Frame() {}

func (*BridgeFrame_End) isBridgeFrame_Frame() {}

// First client frame: names the RPC and carries request metadata.
type BridgeCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full gRPC method path, e.g. "/vmon.v1.SandboxService/Exec".
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// ASCII request metadata (e.g. "authorization"). Binary metadata is not
	// supported over the bridge.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeCall) Reset() {
	*x = BridgeCall{}
	mi := &file_vmon_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeCall) ProtoMessage() {}

func (x *BridgeCall) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeCall.ProtoReflect.Descriptor instead.
func (*BridgeCall) Descriptor() ([]byte, []int) {
	return file_vmon_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeCall) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BridgeCall) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Client half-close: no further request messages will follow.
type BridgeHalfClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeHalfClose) Reset() {
	*x = BridgeHalfClose{}
	mi := &file_vmon_v1_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeHalfClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeHalfClose) ProtoMessage() {}

func (x *BridgeHalfClose) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeHalfClose.ProtoReflect.Descriptor instead.
func (*BridgeHalfClose) Descriptor() ([]byte, []int) {
	return file_vmon_v1_bridge_proto_rawDescGZIP(), []int{2}
}

// Terminal server frame: gRPC status + trailers for the RPC.
type BridgeEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric gRPC status code (0 = OK).
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Status message (empty on OK).
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ASCII trailer metadata (carries `vmon-code` on failures).
	Trailers      map[string]string `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEnd) Reset() {
	*x = BridgeEnd{}
	mi := &file_vmon_v1_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEnd) ProtoMessage() {}

func (x *BridgeEnd) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEnd.ProtoReflect.Descriptor instead.
func (*BridgeEnd) Descriptor() ([]byte, []int) {
	return file_vmon_v1_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *BridgeEnd) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BridgeEnd) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BridgeEnd) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

var File_vmon_v1_bridge_proto protoreflect.FileDescriptor

const file_vmon_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x14vmon/v1/bridge.proto\x12\avmon.v1\"\xc0\x01\n" +
	"\vBridgeFrame\x12)\n" +
	"\x04call\x18\x01 \x01(\v2\x13.vmon.v1.BridgeCallH\x00R\x04call\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\fH\x00R\amessage\x129\n" +
	"\n" +
	"half_close\x18\x03 \x01(\v2\x18.vmon.v1.BridgeHalfCloseH\x00R\thalfClose\x12&\n" +
	"\x03end\x18\x04 \x01(\v2\x12.vmon.v1.BridgeEndH\x00R\x03endB\a\n" +
	"\x05frame\"\xa0\x01\n" +
	"\n" +
	"BridgeCall\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12=\n" +
	"\bmetadata\x18\x02 \x03(\v2!.vmon.v1.BridgeCall.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fBridgeHalfClose\"\xb8\x01\n" +
	"\tBridgeEnd\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\btrailers\x18\x03 \x03(\v2 .vmon.v1.BridgeEnd.TrailersEntryR\btrailers\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B2Z0github.com/stencil-hq/vibemon/sdk/go/internal/pbb\x06proto3"

var (
	file_vmon_v1_bridge_proto_rawDescOnce sync.Once
	file_vmon_v1_bridge_proto_rawDescData []byte
)

func file_vmon_v1_bridge_proto_rawDescGZIP() []byte {
	file_vmon_v1_bridge_proto_rawDescOnce.Do(func() {
		file_vmon_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmon_v1_bridge_proto_rawDesc), len(file_vmon_v1_bridge_proto_rawDesc)))
	})
	return file_vmon_v1_bridge_proto_rawDescData
}

var file_vmon_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vmon_v1_bridge_proto_goTypes = []any{
	(*BridgeFrame)(nil),     // 0: vmon.v1.BridgeFrame
	(*BridgeCall)(nil),      // 1: vmon.v1.BridgeCall
	(*BridgeHalfClose)(nil), // 2: vmon.v1.BridgeHalfClose
	(*BridgeEnd)(nil),       // 3: vmon.v1.BridgeEnd
	nil,                     // 4: vmon.v1.BridgeCall.MetadataEntry
	nil,                     // 5: vmon.v1.BridgeEnd.TrailersEntry
}
var file_vmon_v1_bridge_proto_depIdxs = []int32{
	1, // 0: vmon.v1.BridgeFrame.call:type_name -> vmon.v1.BridgeCall
	2, // 1: vmon.v1.BridgeFrame.half_close:type_name -> vmon.v1.BridgeHalfClose
	3, // 2: vmon.v1.BridgeFrame.end:type_name -> vmon.v1.BridgeEnd
	4, // 3: vmon.v1.BridgeCall.metadata:type_name -> vmon.v1.BridgeCall.MetadataEntry
	5, // 4: vmon.v1.BridgeEnd.trailers:type_name -> vmon.v1.BridgeEnd.TrailersEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vmon_v1_bridge_proto_init() }
func file_vmon_v1_bridge_proto_init() {
	if File_vmon_v1_bridge_proto != nil {
		return
	}
	file_vmon_v1_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*BridgeFrame_Call)(nil),
		(*BridgeFrame_Message)(nil),
		(*BridgeFrame_HalfClose)(nil),
		(*BridgeFrame_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmon_v1_bridge_proto_rawDesc), len(file_vmon_v1_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vmon_v1_bridge_proto_goTypes,
		DependencyIndexes: file_vmon_v1_bridge_proto_depIdxs,
		MessageInfos:      file_vmon_v1_bridge_proto_msgTypes,
	}.Build()
	File_vmon_v1_bridge_proto = out.File
	file_vmon_v1_bridge_proto_goTypes = nil
	file_vmon_v1_bridge_proto_depIdxs = nil
}
